### ISSUE TITLE
Web tests do not run after install

### ISSUE THREAD

**Issue by ghost** [nowol79/webpagetest#2]
Hi!
The docker setup went perfectly (and this is a SUPER useful image! thank you). 
# However after submitting a test, it appears that no tests actually can move forward: for example:

test Setup:
![image](https://cloud.githubusercontent.com/assets/18490728/16412381/ed10238e-3cf9-11e6-89eb-a82c54a1221e.png)

test Queued:
![image](https://cloud.githubusercontent.com/assets/18490728/16412362/dcc2411a-3cf9-11e6-883b-502676ca03fb.png)

tests Never run: (this is approximately 10 minutes after the first submission)
![image](https://cloud.githubusercontent.com/assets/18490728/16412470/67dcad76-3cfa-11e6-97d3-7c459083ab5d.png)

**Comment by ghost** [comment]
Please close: I see now in the docker build there is a copy of the *.ini files.

**Comment by michelob** [comment]
Hello, @ghost

How did you get the image/wpt to pick up these *.ini files? 

I cannot seem to get this to work. 

(that is, webpagetest has no locations when run privately with this image.)
